# Generated by Django 4.1.6 on 2023-02-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('category_productAmount', models.IntegerField(blank=True, null=True)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('full_price', models.IntegerField(blank=True, null=True)),
                ('availability', models.IntegerField(blank=True, null=True)),
                ('orders', models.IntegerField(blank=True, null=True)),
                ('product_rating', models.FloatField(blank=True, null=True)),
                ('seller_id', models.IntegerField(blank=True, null=True)),
                ('seller_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seller_link', models.CharField(blank=True, max_length=70, null=True)),
                ('seller_description', models.TextField(blank=True, null=True)),
                ('seller_registrationDate', models.IntegerField(blank=True, null=True)),
                ('seller_rating', models.FloatField(blank=True, null=True)),
                ('seller_reviews', models.IntegerField(blank=True, null=True)),
                ('seller_orders', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('id',),
            },
        ),
    ]
